### ISSUE TITLE
bug: Open From Feed Fails When Requiring Credentials

### ISSUE THREAD

**Issue by 304NotModified** [304NotModified/NuGetPackageExplorer#3]
copy of https://npe.codeplex.com/workitem/136

> We are using a private nuget feed that requires us to provide our network credentials. Although the package explorer in VS works fine with this feed, the Nuget Package Explorer does not. It returns a 401 status.

**Comment by WiteCastle** [comment]
I'm still getting a 401 status from a private feed hosted on Visual Studio Online (Team Services). I can't figure out how to configure my credentials. Is there a way to do so?

**Comment by kfrancis** [comment]
Still seeing this issue in 3.15.0
